[package]
name = "sessions-app"
version.workspace = true
edition.workspace = true

[dependencies]
sails-rs = {workspace = true, features = ["debug"]}
session-service = { path = "../../session-service" }
